import { Cafe, FilterItem, Review } from "@/types/cafe";

export const KG_CAFES: Cafe[] = [
  {
    id: "c01",
    name: "스트럭처 커피 로스터스",
    shortName: "스트럭처 커피",
    neigh: "강남구 역삼동",
    addr: "서울 강남구 테헤란로 152",
    x: 420,
    y: 420,
    lat: 37.5008,
    lng: 127.0299,
    distance: 0.18,
    hours: "매일 07:30 - 22:00",
    phone: "02-123-4567",
    priceLevel: 2,
    avgPrice: "아메리카노 5,500원",
    capacity: 68,
    score: 94,
    stars: 4.8,
    reviewCount: 312,
    levels: { power: 4, wifi: 4, quiet: 4, space: 3 },
    pros: ["콘센트 많음", "와이파이 빠름", "조용함", "2층 단독석"],
    cons: [],
    limits: [],
    tags: ["24시간", "대형석", "스터디카페 스타일"],
    hero: "warm",
    verified: true,
    trending: "+12%",
    openNow: true,
    crowd: 0.42,
    peakHours: [15, 16, 17, 20],
  },
  {
    id: "c02",
    name: "노트 앤 커피 — 강남점",
    shortName: "노트 앤 커피",
    neigh: "강남구 역삼동",
    addr: "서울 강남구 테헤란로 221",
    x: 790,
    y: 380,
    lat: 37.5011,
    lng: 127.0404,
    distance: 0.32,
    hours: "평일 08:00 - 23:00 · 주말 09:00 - 22:00",
    priceLevel: 2,
    avgPrice: "아메리카노 4,800원",
    capacity: 52,
    score: 88,
    stars: 4.6,
    reviewCount: 187,
    levels: { power: 4, wifi: 3, quiet: 3, space: 4 },
    pros: ["넓은 테이블", "콘센트 충분", "화상회의 가능"],
    cons: ["오후 2~5시 혼잡"],
    limits: [],
    tags: ["넓은테이블", "화상회의OK", "단체석"],
    hero: "cream",
    verified: true,
    openNow: true,
    crowd: 0.78,
    peakHours: [14, 15, 16, 17],
  },
  {
    id: "c03",
    name: "페이퍼라이트 역삼",
    shortName: "페이퍼라이트",
    neigh: "강남구 역삼동",
    addr: "서울 강남구 논현로 508",
    x: 1150,
    y: 560,
    lat: 37.4995,
    lng: 127.0506,
    distance: 0.54,
    hours: "매일 09:00 - 22:00",
    priceLevel: 3,
    avgPrice: "아메리카노 6,500원",
    capacity: 34,
    score: 79,
    stars: 4.5,
    reviewCount: 96,
    levels: { power: 3, wifi: 4, quiet: 4, space: 2 },
    pros: ["분위기 좋음", "조용함", "밝은 조명"],
    cons: ["자리 적음", "가격대 높음"],
    limits: ["2시간 이용 권장"],
    tags: ["조용함", "북카페", "2시간제한"],
    hero: "paper",
    verified: true,
    openNow: true,
    crowd: 0.55,
    peakHours: [11, 14, 15],
  },
  {
    id: "c04",
    name: "코너스톤 브루잉",
    shortName: "코너스톤",
    neigh: "강남구 삼성동",
    addr: "서울 강남구 영동대로 416",
    x: 520,
    y: 680,
    lat: 37.4984,
    lng: 127.0327,
    distance: 0.71,
    hours: "매일 24시간",
    priceLevel: 2,
    avgPrice: "아메리카노 5,000원",
    capacity: 120,
    score: 91,
    stars: 4.7,
    reviewCount: 428,
    levels: { power: 4, wifi: 4, quiet: 3, space: 4 },
    pros: ["24시간 운영", "좌석 여유", "콘센트 전석"],
    cons: ["새벽 청소시간 2~4시 소음"],
    limits: [],
    tags: ["24시간", "전석콘센트", "밤샘가능"],
    hero: "dark",
    verified: true,
    openNow: true,
    crowd: 0.34,
    peakHours: [13, 14, 20, 21, 22],
  },
  {
    id: "c05",
    name: "밋 앤 빈 선릉",
    shortName: "밋 앤 빈",
    neigh: "강남구 대치동",
    addr: "서울 강남구 선릉로 428",
    x: 980,
    y: 720,
    lat: 37.4981,
    lng: 127.0458,
    distance: 0.84,
    hours: "매일 08:00 - 21:00",
    priceLevel: 1,
    avgPrice: "아메리카노 3,900원",
    capacity: 28,
    score: 62,
    stars: 4.2,
    reviewCount: 64,
    levels: { power: 2, wifi: 3, quiet: 2, space: 2 },
    pros: ["가격 저렴", "따뜻한 분위기"],
    cons: ["콘센트 일부석만", "오후 붐빔"],
    limits: ["노트북 2시간 제한"],
    tags: ["저렴함", "2시간제한"],
    hero: "warm",
    verified: false,
    openNow: true,
    crowd: 0.88,
    peakHours: [13, 14, 15, 16],
  },
  {
    id: "c06",
    name: "레이어드 워크스페이스",
    shortName: "레이어드",
    neigh: "강남구 역삼동",
    addr: "서울 강남구 강남대로 398",
    x: 260,
    y: 560,
    lat: 37.4995,
    lng: 127.0253,
    distance: 0.22,
    hours: "평일 07:00 - 24:00 · 주말 10:00 - 22:00",
    priceLevel: 3,
    avgPrice: "아메리카노 6,000원",
    capacity: 82,
    score: 96,
    stars: 4.9,
    reviewCount: 541,
    levels: { power: 4, wifi: 4, quiet: 4, space: 4 },
    pros: ["전석 콘센트·USB 포트", "기가 와이파이", "모니터 대여", "개인 부스"],
    cons: ["주말 대기 있음"],
    limits: [],
    tags: ["개인부스", "USB포트", "모니터대여", "프리미엄"],
    hero: "cream",
    verified: true,
    trending: "+38%",
    openNow: true,
    crowd: 0.62,
    peakHours: [10, 11, 14, 15, 19, 20],
  },
  {
    id: "c07",
    name: "포지티브 브루 — 논현",
    shortName: "포지티브 브루",
    neigh: "강남구 논현동",
    addr: "서울 강남구 학동로 225",
    x: 720,
    y: 220,
    lat: 37.5026,
    lng: 127.0384,
    distance: 0.46,
    hours: "매일 08:00 - 22:00",
    priceLevel: 2,
    avgPrice: "아메리카노 5,200원",
    capacity: 44,
    score: 72,
    stars: 4.4,
    reviewCount: 128,
    levels: { power: 3, wifi: 3, quiet: 3, space: 3 },
    pros: ["창가 자리 좋음", "햇빛 밝음"],
    cons: ["점심시간대 시끄러움"],
    limits: [],
    tags: ["창가석", "중규모"],
    hero: "warm",
    verified: true,
    openNow: true,
    crowd: 0.58,
    peakHours: [12, 13, 15],
  },
  {
    id: "c08",
    name: "리프라이트 라운지",
    shortName: "리프라이트",
    neigh: "강남구 역삼동",
    addr: "서울 강남구 테헤란로 87길 46",
    x: 1260,
    y: 320,
    lat: 37.5017,
    lng: 127.0538,
    distance: 0.62,
    hours: "평일 09:00 - 22:00",
    priceLevel: 2,
    avgPrice: "아메리카노 5,000원",
    capacity: 36,
    score: 45,
    stars: 3.9,
    reviewCount: 58,
    levels: { power: 1, wifi: 2, quiet: 2, space: 2 },
    pros: ["위치 좋음"],
    cons: ["콘센트 거의 없음", "노트북 사용 눈치"],
    limits: ["노트북 금지", "1인 1음료"],
    tags: ["노트북금지", "1인1음료"],
    hero: "paper",
    verified: true,
    openNow: false,
    crowd: 0.25,
    peakHours: [12, 13],
  },
];

export const KG_FILTERS: FilterItem[] = [
  { id: "power", label: "콘센트", icon: "plug" },
  { id: "wifi", label: "와이파이", icon: "wifi" },
  { id: "quiet", label: "조용함", icon: "volume" },
  { id: "space", label: "공간여유", icon: "layout" },
  { id: "open24", label: "24시간", icon: "clock" },
  { id: "noLimit", label: "시간제한 없음", icon: "check" },
  { id: "notebook", label: "노트북 OK", icon: "laptop" },
  { id: "cheap", label: "5천원 이하", icon: "coin" },
];

const BASE_REVIEWS: Review[] = [
  {
    initials: "지수",
    name: "지수",
    avatarBg: "#F5A524",
    stars: 5,
    date: "3일 전",
    visits: 7,
    text: "취준생 기준 최고의 장소. 콘센트 자리 거의 전석 확보됐고 오전 9시에 가면 1층 창가 자리 잡을 수 있어요. 화장실도 깔끔해서 장기체류 가능.",
    tags: ["콘센트많음", "장기체류", "조용함"],
    badge: "카공 단골",
  },
  {
    initials: "민준",
    name: "민준",
    avatarBg: "#3772cf",
    stars: 4,
    date: "1주 전",
    visits: 3,
    text: "화상회의 하기 좋았어요. 와이파이 속도 측정해봤는데 업/다운 모두 200Mbps 넘음. 다만 오후 3시 이후로는 옆자리랑 가까워서 통화는 복도에서 하는 게 좋아요.",
    tags: ["와이파이빠름", "화상회의OK"],
    badge: "프리랜서",
  },
  {
    initials: "유진",
    name: "유진",
    avatarBg: "#0fa76e",
    stars: 5,
    date: "2주 전",
    visits: 12,
    text: "대학원생인데 논문 쓸 때 여기 자주 옵니다. 사장님도 눈치 안 주시고 5시간 넘게 있어도 편해요. 커피값이 좀 있는 편이긴 한데 환경값이라고 생각하면 납득.",
    tags: ["장기체류OK", "눈치없음"],
    badge: "대학원생",
  },
];

export function getReviewsForCafe(cafe: Cafe): Review[] {
  const reviews = [...BASE_REVIEWS];
  if (cafe.cons.includes("오후 2~5시 혼잡")) {
    reviews.push({
      initials: "준호",
      name: "준호",
      avatarBg: "#8B5CF6",
      stars: 3,
      date: "5일 전",
      visits: 2,
      text: "오전엔 최고인데 오후 2시 넘어가면 단체 손님 오면서 갑자기 시끄러워짐. 타이밍 잘 맞추면 좋은 곳.",
      tags: ["시간대주의"],
    });
  }
  return reviews;
}
